"""Add job id to detections

Revision ID: 5667a81030f9
Revises: b6a6cc95e19e
Create Date: 2026-07-25 01:07:30.850195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5667a81030f9'
down_revision = 'b6a6cc95e19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_detections_job_id'), ['job_id'], unique=False)
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_detections_job_id'))
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
