"""Create detections table

Revision ID: 586954b390fc
Revises: f6cf8febdebd
Create Date: 2026-07-15 15:35:18.533217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586954b390fc'
down_revision = 'f6cf8febdebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=True),
    sa.Column('matched_pattern', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_attack_type'), ['attack_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_source_ip'), ['source_ip'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_source_ip'))
        batch_op.drop_index(batch_op.f('ix_detections_severity'))
        batch_op.drop_index(batch_op.f('ix_detections_attack_type'))

    op.drop_table('detections')
    # ### end Alembic commands ###
