"""add detection investigation fields

Revision ID: 63b3ded06bd3
Revises: 586954b390fc
Create Date: 2026-07-16 18:52:00.554635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b3ded06bd3'
down_revision = '586954b390fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('http_method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('request_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('raw_log', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_column('raw_log')
        batch_op.drop_column('status_code')
        batch_op.drop_column('request_path')
        batch_op.drop_column('http_method')

    # ### end Alembic commands ###
